name: tt_online
description: online tt

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.2.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #firebase stuff
  firebase_core: ^1.20.0
  firebase_analytics: ^9.3.0
  firebase_auth: ^3.5.1
  cloud_firestore: ^3.4.1
  #################
  intl: ^0.17.0
  url_launcher: ^6.1.5
  slide_digital_clock: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios:  true
  image_path: "assets/icon/icon.png"
#To change icon
#flutter pub get
#flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/images/Linkedin_logo.png
    - assets/images/Github_logo.png
    - assets/images/Sleeping.png
    - assets/images/sunset.png
    - assets/images/psychedelic_triangle.gif
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Thin.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
    - family: Channel
      fonts:
        - asset: assets/fonts/Channel.ttf
    - family: SF
      fonts:
        - asset: assets/fonts/SanFrancisco.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Sherlyn
      fonts:
        - asset: assets/fonts/Sherlyn.ttf
